channels:
  - bioconda
  - conda-forge
dependencies:
  - python=3
  - snakemake
  - pandas>=0.24
  - pypy3.5
  - plink
  - scipy
  - numpy
  - requests>=2.18.0
  - parallel
  - httplib2  
  - crcmod
  - pip
  - psutil
  - pip:
    - pronto
    - pyspark
    - psutil

