# Output config
temp_dir: 'tmp'
gs_dir: 'gs://genetics-portal-staging/v2d'

# GWAS Catalog curated data
gwas_cat_min_pvalue: 5e-8 # Minimum p-value to be included
gwas_cat_cluster_dist_kb: 500 # ± Distance in Kb
gwas_cat_cluster_min_loci: 10 # Minimum number of reported loci for that study to be included in the clustering analysis
gwas_cat_cluster_multi_proportion: 0.3 # For a given study, if more than this proportion of loci are multi-signals (>1 signal within gwas_cat_cluster_dist_kb), the study will be clustered

# Summary statistics finemapping pipeline output files
gcs_sumstat_pattern: 'gs://genetics-portal-sumstats-b38/unfiltered/gwas/*.parquet'
toploci: 'gs://genetics-portal-staging/finemapping/190612/top_loci/part-00000-5e9aef09-9aea-4fab-898f-0725f0bbf865-c000.json.gz'
credsets: 'gs://genetics-portal-staging/finemapping/190612/credset/_SUCCESS' # Need the whole directory, so passing the _SUCCSS file instead to trick snakemake

# UK Biobank (Neale V2 and SAIGE) sumstat manifest files
ukb_manifest: 'gs://genetics-portal-input/ukb_phenotypes/neale2_saige_study_manifest.190430.tsv'
ukb_efo_curation: 'gs://genetics-portal-input/ukb_phenotypes/ukb_efo_annotation.190828.json'

# Trait category / therapeutic area
efo_therapeutic_areas: 'configs/therapeutic_areas.tsv' # List of therapeutic area labels
therapeutic_area_unknown_label: 'Uncategorised'

# # Neale et al UK Biobank manifest file
# neale_manifest: 'genetics-portal-input/uk_biobank_data/em21/neale_summary_statistics_20170915/cleaned_data/phenosummary_final_11898_18597.fixed.curation_manifest.tsv'
# neale_efo_icd10: 'genetics-portal-input/uk_biobank_data/em21/neale_summary_statistics_20170915/efo_curation/v1_2018_07_05/phenosummary_final_11898_18597.fixed.curation_manifest - QC of ICD10 traits - Iteration 1.csv'
# neale_efo_self: 'genetics-portal-input/uk_biobank_data/em21/neale_summary_statistics_20170915/efo_curation/v1_2018_07_05/phenosummary_final_11898_18597.fixed.curation_manifest - QC of self-reported traits - Iteration 1.csv'
# neale_categories: 'genetics-portal-input/uk_biobank_data/em21/neale_summary_statistics_20170915/PheWAS_categories/neale_cateogries.v2.tsv'

# LD table
url_1000G: 'gs://genetics-portal-input/1000Genomes_phase3/plink_format_b38'
gwascat_2_superpop: 'configs/gwascat_superpopulation_lut.curated.v2.tsv'
ld_window: 500
min_r2: 0.5

# Variant index
var_index_sitelist: 'gs://genetics-portal-staging/variant-annotation/190129/variant-annotation.sitelist.tsv.gz'
