# Params
version: 'v1_180703' # Version number

# Output config
temp_dir: 'temp'
gs_bucket: 'genetics-portal-data'
gs_dir: 'em21_data'

# Finemapping files
credset: 'uk_biobank_analysis/em21/neale_summary_statistics_20170915/finemapping/results/neale_ukb_uk10kref_180502.crediblesets.long.varids.tsv.gz'
variant_map: 'uk_biobank_data/em21/neale_summary_statistics_20170915/cleaned_data/clean/50.nealeUKB_20170915.assoc.clean.tsv.gz'
